apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.name }}-pv-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistentVolume.size }}
  storageClassName: {{ .Values.storageClass }}
