apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 3306
  selector:
    app: {{ .Values.wordpress.name }}
    tier: mysql

