apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wordpress.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.wordpress.name }}
      tier: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.wordpress.name }}
        tier: web
    spec:
      containers:
        - image: wordpress:{{ .Values.wordpress.imageTag }}
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.mysql.name }}:3306
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-user-password-9m7k5b4k2m
                  key: passworduser
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-user-4t5mcf8dkm
                  key: username
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-database-4f74mgddt5
                  key: database
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.wordpress.name }}-pv-claim

