apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
  selector:
    app: {{ .Values.wordpress.name }}
    tier: web
  type: LoadBalancer

